# Generated by Django 3.2.12 on 2025-05-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0003_roomtype_roomvariety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roomdetail',
            name='variety',
        ),
    ]
