# Generated by Django 3.2.12 on 2025-05-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0004_auto_20250507_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.roomtype'),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.roomvariety'),
        ),
    ]
