# Generated by Django 3.2.12 on 2025-05-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_auto_20250507_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roomdetail',
            name='variety',
        ),
    ]
