# Generated by Django 3.2.12 on 2025-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0006_auto_20250508_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='room_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='variety',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
