# Generated by Django 3.2.12 on 2025-05-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_auto_20250508_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.amenity'),
        ),
    ]
