# Generated by Django 3.2.12 on 2025-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0009_remove_roomdetail_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='tenant_app.Amenity'),
        ),
    ]
