# Generated by Django 3.2.12 on 2025-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0010_roomdetail_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='tenant_app.Amenity'),
        ),
    ]
