# Generated by Django 3.2.12 on 2025-05-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0011_alter_roomdetail_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='amenities',
        ),
    ]
