# Generated by Django 3.2.12 on 2025-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0012_remove_roomdetail_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Room Image'),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='number_of_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Persons'),
        ),
    ]
