# Generated by Django 3.2.12 on 2025-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0013_auto_20250518_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='room_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
