# Generated by Django 3.2.12 on 2025-05-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0015_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tenant_app.roomdetail'),
        ),
    ]
