# Generated by Django 3.2.12 on 2025-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0016_roomimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
