# Generated by Django 3.2.12 on 2025-05-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0017_setting_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenant_app.setting'),
        ),
    ]
