# Generated by Django 3.2.12 on 2025-05-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0019_remove_setting_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='setting',
        ),
    ]
