# Generated by Django 3.2.12 on 2025-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0020_remove_roomdetail_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
