# Generated by Django 3.2.12 on 2025-05-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_amenity_amenitypublic'),
        ('tenant_app', '0023_hotelamenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenityroom',
            name='amenity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.amenitypublic'),
        ),
    ]
