# Generated by Django 3.2.12 on 2025-05-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0025_alter_roomdetail_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenity',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='tenant_app.setting'),
        ),
    ]
