# Generated by Django 3.2.12 on 2025-05-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0026_hotelamenity_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelamenity',
            name='amenity_name',
        ),
    ]
