# Generated by Django 3.2.12 on 2025-05-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_amenity_amenitypublic'),
        ('tenant_app', '0027_remove_hotelamenity_amenity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenity',
            name='amenity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.amenitypublic'),
        ),
    ]
