# Generated by Django 3.2.12 on 2025-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0028_hotelamenity_amenity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='amenities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
