# Generated by Django 3.2.12 on 2025-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0029_roomdetail_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='name',
            field=models.CharField(max_length=250, verbose_name='First name'),
        ),
    ]
