# Generated by Django 3.2.12 on 2025-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0030_auto_20250531_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
