# Generated by Django 3.2.12 on 2025-04-26 06:02

from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('tag_line', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(default='', max_length=15, unique=True)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('confirm_password', models.CharField(max_length=500, null=True)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(default='', max_length=6)),
                ('otptime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'OTP',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(default='', max_length=255)),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('tenant_name', models.CharField(default='', max_length=255, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Subscribed_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.plans')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_id', to='admin_app.clientdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.features')),
                ('plan_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.plans')),
            ],
            options={
                'verbose_name_plural': 'Planned Features',
            },
        ),
    ]
