# Generated by Django 3.2.12 on 2025-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='tenant',
        ),
    ]
