# Generated by Django 3.2.12 on 2025-05-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_amenity_tenant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='AmenityPublic',
        ),
    ]
